// Generated by tools/alien-bake.mjs — rerun it rather than editing this file.
// What the baked loop videos beside it hold (src/render/scenes/alien/index.ts reads it).
export const BAKED = {
  "fps": 120,
  "width": 1280,
  "height": 720,
  "loops": [
    {
      "clip": "expressive",
      "file": "loop0.mp4",
      "frames": 480,
      "seconds": 4,
      "pivot": [
        0.5005,
        -1.213
      ]
    },
    {
      "clip": "twist",
      "file": "loop1.mp4",
      "frames": 288,
      "seconds": 2.4,
      "pivot": [
        0.48,
        -0.1791
      ]
    },
    {
      "clip": "toprock2",
      "file": "loop2.mp4",
      "frames": 400,
      "seconds": 3.3333333333333335,
      "pivot": [
        0.5062,
        -0.026
      ]
    }
  ]
} as const;
