#!/usr/bin/env node
// Bakes the Alien scene's loops to video: renders every frame of every loop
// on the bake page (src/render/scenes/alien/bakePage.ts, served by the dev
// server at /tools/alien-bake/), saves them as PNGs, and encodes each loop
// with ffmpeg (H.264, which every browser and TV the app targets decodes) into
// src/render/scenes/alien/loops/, with a manifest.ts the scene reads: the
// frame rate, the frame size, and per loop its clip, frame count, length and
// Bounce pivot.
//
//   npm run dev -- --port 5321
//   node tools/alien-bake.mjs --port 5321 [--fps 120] [--size 1280x720] [--crf 22] [--loops 0,2]
//
// --fps is frames per second of dance at 1× speed. More than the screen's
// rate is the point: when Move plays a loop slower, each screen refresh still
// gets a new frame (half speed at 120 is 60 frames a second), with no blending
// between frames, which would double the wire's thin lines. ffmpeg comes from
// $FFMPEG, else the PATH. Rerun after changing the alien, a loop's clip or
// camera, or the look; tests/alien.test.ts checks the manifest still matches
// LOOPS.
import { chromium } from "playwright";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const args = process.argv.slice(2);
const opt = (name, def) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : def;
};
const port = opt("port", "5173");
const fps = Number(opt("fps", "120"));
const [width, height] = opt("size", "1280x720").split("x").map(Number);
// 22 keeps the face's fine mesh; 26 smeared it (2026-10-05, the scene record).
const crf = opt("crf", "22");
const only = opt("loops", null)?.split(",").map(Number) ?? null;
const ffmpeg = process.env.FFMPEG || "ffmpeg";
const outDir = path.resolve("src/render/scenes/alien/loops");
mkdirSync(outDir, { recursive: true });

const browser = await chromium.launch({
  channel: "chromium",
  args: ["--enable-gpu", "--use-angle=metal", "--enable-gpu-rasterization", "--ignore-gpu-blocklist"],
});
const page = await (await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width, height } })).newPage();
page.on("pageerror", (e) => console.error("bake page:", e.message));
await page.goto(`https://localhost:${port}/tools/alien-bake/index.html?w=${width}&h=${height}`);
const info = await page.evaluate(() => window.__bake.ready);

const manifest = { fps, width, height, loops: [] };
for (const [i, loop] of info.loops.entries()) {
  const frames = Math.round(loop.seconds * fps);
  const file = `loop${i}.mp4`;
  manifest.loops.push({ clip: loop.clip, file, frames, seconds: frames / fps, pivot: loop.pivot.map((v) => +v.toFixed(4)) });
  if (only && !only.includes(i)) continue;
  const dir = mkdtempSync(path.join(tmpdir(), `alien-bake-${i}-`));
  const t0 = Date.now();
  for (let f = 0; f < frames; f++) {
    const url = await page.evaluate(([l, p]) => window.__bake.frame(l, p), [i, f / frames]);
    writeFileSync(path.join(dir, `${String(f).padStart(5, "0")}.png`), Buffer.from(url.split(",")[1], "base64"));
  }
  execFileSync(ffmpeg, [
    "-v", "error", "-y", "-framerate", String(fps), "-i", path.join(dir, "%05d.png"),
    "-c:v", "libx264", "-preset", "slow", "-crf", crf, "-pix_fmt", "yuv420p", "-movflags", "+faststart", "-an",
    path.join(outDir, file),
  ]);
  rmSync(dir, { recursive: true, force: true });
  const kb = Math.round(statSync(path.join(outDir, file)).size / 1024);
  console.log(`loop ${i} (${loop.clip}): ${frames} frames in ${((Date.now() - t0) / 1000).toFixed(0)} s -> ${file}, ${kb} KB`);
}
const manifestTs =
  "// Generated by tools/alien-bake.mjs — rerun it rather than editing this file.\n" +
  "// What the baked loop videos beside it hold (src/render/scenes/alien/index.ts reads it).\n" +
  `export const BAKED = ${JSON.stringify(manifest, null, 2)} as const;\n`;
writeFileSync(path.join(outDir, "manifest.ts"), manifestTs);
console.log("manifest:", path.join(outDir, "manifest.ts"));
await browser.close();
